-- RUN AS SYSTEM USER

-- CHECK AFL PAL FUNCTIONS ARE INSTALLED
SELECT * FROM SYS.AFL_FUNCTIONS WHERE PACKAGE_NAME='PAL';

-- START SCRIPT SERVER
ALTER SYSTEM ALTER CONFIGURATION ('daemon.ini', 'SYSTEM') SET ('scriptserver', 'instances') = '1' WITH RECONFIGURE;

-- CREATE DEVELOPMENT USER
CREATE USER DEVUSER PASSWORD Password1;

-- AUTHORIZE EXECUTION OF PAL PROCEDURES
GRANT AFL__SYS_AFL_AFLPAL_EXECUTE TO DEVUSER;

-- AUTHORIZE DEVUSER TO CREATE R FUNCTIONS
GRANT CREATE R SCRIPT TO DEVUSER;

-- GRANT ACCESS TO APPLICATION SCHEMA
GRANT SELECT ON SCHEMA AFM TO DEVUSER;

-- AFL MODELER

-- ENABLE MODELING
GRANT MODELING TO DEVUSER;

-- ENABLE HANA NATIVE DEVELOPMENT
GRANT EXECUTE ON REPOSITORY_REST TO DEVUSER;
GRANT REPO.READ, REPO.EDIT_NATIVE_OBJECTS, REPO.ACTIVATE_NATIVE_OBJECTS, REPO.MAINTAIN_NATIVE_PACKAGES ON ".REPO_PACKAGE_ROOT" TO DEVUSER;

-- GRANT REPOSITORY TECH USER ACCESS TO APPLICATION SCHEMAS
GRANT SELECT ON SCHEMA AFM TO _SYS_REPO;

-----------------------------------

-- RUN AS DEVUSER
GRANT SELECT, INSERT, DELETE ON SCHEMA DEVUSER TO _SYS_REPO;
